import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/NavBar";
import Foter from "./ui/Foter";
import AuthProvider from "./ui/AuthProvider";
import { Suspense } from "react";
import Loading from "./ui/Loading";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <AuthProvider>
       <NavBar></NavBar>
       <Suspense fallback={<Loading></Loading>}>
      
        {children}
        </Suspense>
        
        <Foter></Foter>
        </AuthProvider>
        </body>
       
    </html>
  );
}
